### ISSUE TITLE
Refactor WriteFile

### ISSUE THREAD

**Issue by Costava** [cassepipe/makeheaders#2]
Link to current latest `WriteFile` function:  
https://github.com/cassepipe/makeheaders/blob/03edfb03b41ed64dfedb4b8d2bd6719d78b49a40/makeheaders.c#L916-L945

---

`ft_strjoin3` calls `SafeMalloc` which either succeeds or calls `exit(1);` so `if (path == 0)` will never be entered and the whole `if` can be removed.

---

If the `else` branch is entered but `fopen(zFilename, "w");` errors, then `path` will be used as uninitialized memory at `fprintf(stderr, "Could not open %s\n", path);`

---

The `if (pOut == 0)` branch leaks memory if `ft_strjoin3` was called earlier since the `return 1;` happens without first freeing `path`. Not a high impact issue since `makeheaders` is a short-lived program and the amount of memory leaked is not large.

**Comment by cassepipe** [comment]
Hi ! Are you actually using this fork just for the sake of the output option ?

If you want to make a pull request, please do.

**Comment by cassepipe** [comment]
Actually I just went ahead and fixed it (or so I believe)

**Comment by Costava** [comment]
Wow. Fast response.

https://github.com/cassepipe/makeheaders/blob/77c09eb9f993adefbdd8c98e909a6e9c6538da6d/makeheaders.c#L916-L941

> Actually I just went ahead and fixed it (or so I believe)

I don't see any problems either.

> Are you actually using this fork just for the sake of the output option ?

Not currently using any version of `makeheaders`. I was looking at the `makeheaders` documentation and my thought was that I would want all the output of `makeheaders` in a dedicated folder, so I went looking for versions with that option.
