### ISSUE TITLE
Makeheaders doc link broken

### ISSUE THREAD

**Issue by ntrel** [cassepipe/makeheaders#3]
Hi,
Unfortunately this link no longer works:
https://fossil-scm.org/home/doc/trunk/src/makeheaders.html#H0006

I had a quick look in their tree but didn't find it anywhere.

**Comment by cassepipe** [comment]
There you go : https://fossil-scm.org/home/doc/trunk/tools/makeheaders.html

**Comment by ntrel** [comment]
Thanks!
